LABELS_DICT = {
    "person": "người",
    "bicycle": "xe đạp",
    "car": "ô tô",
    "motorcycle": "xe máy",
    "airplane": "máy bay",
    "bus": "xe buýt",
    "train": "tàu",
    "truck": "xe tải",
    "boat": "thuyền",
    "traffic light": "đèn giao thông",
    "fire hydrant": "cột chữa cháy",
    "stop sign": "biển dừng",
    "parking meter": "máy tính tiền đỗ xe",
    "bench": "ghế băng",
    "bird": "con chim",
    "cat": "con mèo",
    "dog": "con chó",
    "horse": "con ngựa",
    "sheep": "con cừu",
    "cow": "con bò",
    "elephant": "con voi",
    "bear": "con gấu",
    "zebra": "ngựa vằn",
    "giraffe": "hươu cao cổ",
    "backpack": "ba lô",
    "umbrella": "ô",
    "handbag": "túi xách",
    "tie": "cà vạt",
    "suitcase": "vali",
    "frisbee": "đĩa bay",
    "skis": "ván trượt",
    "snowboard": "ván trượt tuyết",
    "sports ball": "quả bóng thể thao",
    "kite": "diều",
    "baseball bat": "gậy bóng chày",
    "baseball glove": "găng tay bóng chày",
    "skateboard": "ván trượt",
    "surfboard": "ván lướt sóng",
    "tennis racket": "vợt tennis",
    "bottle": "chai nước",
    "wine glass": "ly rượu",
    "cup": "cốc",
    "fork": "dĩa",
    "knife": "dao",
    "spoon": "muỗng",
    "bowl": "bát",
    "banana": "chuối",
    "apple": "táo",
    "sandwich": "bánh mì kẹp",
    "orange": "cam",
    "broccoli": "bông cải xanh",
    "carrot": "cà rốt",
    "hot dog": "xúc xích",
    "pizza": "pizza",
    "donut": "bánh donut",
    "cake": "bánh kem",
    "chair": "ghế",
    "couch": "ghế sofa",
    "potted plant": "cây trong chậu",
    "bed": "giường",
    "dining table": "bàn ăn",
    "toilet": "bồn cầu",
    "tv": "tivi",
    "laptop": "máy tính xách tay",
    "mouse": "chuột máy tính",
    "remote": "remote điều khiển",
    "keyboard": "bàn phím",
    "cell phone": "điện thoại di động",
    "microwave": "lò vi sóng",
    "oven": "lò nướng",
    "toaster": "máy nướng bánh",
    "sink": "bồn rửa",
    "refrigerator": "tủ lạnh",
    "book": "sách",
    "clock": "đồng hồ",
    "vase": "bình hoa",
    "scissors": "kéo",
    "teddy bear": "gấu bông",
    "hair drier": "máy sấy tóc",
    "toothbrush": "bàn chải đánh răng",
    "barn": "chuồng trại",
    "restaurant": "nhà hàng",
    "goose": "con ngỗng",
}

def get_label_translation(label):
    return LABELS_DICT.get(label, "Không có nghĩa")
